config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'About-My-Site', to: 'pages#about'
  get 'Contact', to: 'pages#contact'

  resources :blog_tests do
  	member do 
   	 get :toggle_status
	end
end
 
	root to: 'pages#home'
end






 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_test.rb
class BlogTest < ApplicationRecord
	enum status: { draft: 0, published: 1 }	
	extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_tests_controller.rb
class BlogTestsController < ApplicationController
  before_action :set_blog_test, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blog_tests
  # GET /blog_tests.json
  def index
    @blog_tests = BlogTest.all
  end

  # GET /blog_tests/1
  # GET /blog_tests/1.json
  def show
  end

  # GET /blog_tests/new
  def new
    @blog_test = BlogTest.new
  end

  # GET /blog_tests/1/edit
  def edit
  end

  # POST /blog_tests
  # POST /blog_tests.json
  def create
    @blog_test = BlogTest.new(blog_test_params)

    respond_to do |format|
      if @blog_test.save
        format.html { redirect_to @blog_test, notice: 'Blog test was successfully created.' }
        format.json { render :show, status: :created, location: @blog_test }
      else
        format.html { render :new }
        format.json { render json: @blog_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_tests/1
  # PATCH/PUT /blog_tests/1.json
  def update
    respond_to do |format|
      if @blog_test.update(blog_test_params)
        format.html { redirect_to @blog_test, notice: 'Blog test was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_test }
      else
        format.html { render :edit }
        format.json { render json: @blog_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_tests/1
  # DELETE /blog_tests/1.json
  def destroy
    @blog_test.destroy
    respond_to do |format|
      format.html { redirect_to blog_tests_url, notice: 'Blog test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def toggle_status
		if  @blog_test.draft?
		@blog_test.published!
		elsif  @blog_test.published?
		@blog_test.draft!
  end

   redirect_to blog_tests_url, notice: 'Post status has been updated.'
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_test
			@blog_test = BlogTest.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_test_params
      params.require(:blog_test).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = BlogTest.all
	@skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	def index
		@portfolios_items = Portfolio.all
	end

	def new
	@portfolios_item = Portfolio.new
	end

	def create 
	@portfolios_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body))

		respond_to do |format|
			if @portfolios_item.save
				format.html { redirect_to portfolios_path, notice: 'Your portfolio is now live.' }
			else 
				format.html { render :new }
			end
		end
	end

def edit
	@portfolios_item = Portfolio.find(params[:id])
	end

  def update
	@portfolios_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolios_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfolios_path, notice: 'The record was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_test }
      else
        format.html { render :edit }
        format.json { render json: @blog_test.errors, status: :unprocessable_entity }
      end
    end
  end

	def show
		@portfolios_item = Portfolio.find(params[:id])
	end	

	def destroy
		# Performs the lookup
		@portfolios_item = Portfolio.find(params[:id])

		# Destroys/delete the record
		@portfolios_item.destroy

		# Redirects
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolios record successfully destroyed.' }
    end
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_tests_helper.rb
module BlogTestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blog_tests/_form.html.erb
<%= form_with(model: blog_test, local: true) do |form| %>
  <% if blog_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_test.errors.count, "error") %> prohibited this blog_test from being saved:</h2>

      <ul>
      <% blog_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_test_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_test_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_tests/edit.html.erb
<h1>Editing Blog Test</h1>

<%= render 'form', blog_test: @blog_test %>

<%= link_to 'Show', @blog_test %> |
<%= link_to 'Back', blog_tests_path %>

app/views/blog_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Tests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_tests.each do |blog_test| %>
      <tr>
        <td><%= blog_test.title %></td>
        <td><%= blog_test.body %></td>
				<td><%= link_to blog_test.status, toggle_status_blog_test_path(blog_test) %></td>
        <td><%= link_to 'Show', blog_test %></td>
        <td><%= link_to 'Edit', edit_blog_test_path(blog_test) %></td>
        <td><%= link_to 'Destroy', blog_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Test', new_blog_test_path %>

app/views/blog_tests/new.html.erb
<h1>New Blog Test</h1>

<%= render 'form', blog_test: @blog_test %>

<%= link_to 'Back', blog_tests_path %>

app/views/blog_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_test.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog_test.body %>
</p>

<%= link_to 'Edit', edit_blog_test_path(@blog_test) %> |
<%= link_to 'Back', blog_tests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApplicatonTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About_Page</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h2>Contact-Page</h2>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>My_First_Blog-Test</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>Blog_Tests</h2>
<%= @posts.inspect %>

<h2>Skills</h2>
<%= @skills.inspect %>

app/views/portfolios/edit.html.erb
<h2>Edit this Portfolio Item</h2>

<%= form_for(@portfolios_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

 <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

 <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1> Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @portfolios_items.each do |portfolio_item| %>
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
<%= link_to 'Delete Portfolios Item', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you Absolutely sure?' } %>
<% end %>

app/views/portfolios/new.html.erb
 <h2>Create a new  Portfolio Item</h2>

<%= form_for(@portfolios_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

 <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolios_item.main_image %>

<h2><%= @portfolios_item.title %></h2>

<em><%= @portfolios_item.subtitle %></em>

<p><%= @portfolios_item.body %></p>